Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 80, host:8600

  config.vm.define "web"

  config.vm.synced_folder "../src", "/home/vagrant/apps/carl-rosemy/src", create: true
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.extra_vars = {
      "is_vagrant" => true
    }
    ansible.groups = {
      "iraya_platform" => ["web"]
    }
    ansible.verbose = true
    ansible.install_mode = "pip"
    ansible.playbook = "playbooks/provision.yml"
  end

end

