- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes

- name: Clone the processing server
  become: yes
  become_user: '{{ app_user.username }}'
  when: git_clone
  git:
    repo: 'https://github.com/csyu1/rosemy.git'
    dest: '{{ app_directory }}'
    accept_hostkey: yes
    update: yes
    force: yes

- name: ensure apps directory is owned by app user
  become: yes
  command: 'chown -R  {{ app_user.username }}:{{ app_user.username }} {{ apps_directory }}'
  changed_when: false

- include: nginx.yml
- include: python.yml
- include: site.yml