---
- name: Install python 3.7 dependencies
  become: true
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - checkinstall
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
    - virtualenv

- name: Extract python 3.7
  become: true
  unarchive:
    src: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz
    dest: /opt/
    remote_src: true
  args:
    creates: /opt/Python-3.7.0/configure

- name: Install python3.7
  become: true
  shell: |
    cd /opt/Python-3.7.0
    ./configure
    sudo make
    sudo make altinstall
  args:
    chdir: /opt/Python-3.7.0
    creates: /usr/local/bin/python3.7

- name: Create virtualenv
  become: yes
  become_user: '{{ app_user.username }}'
  command: virtualenv -p python3.7 {{ venv_directory }} --always-copy
  args:
    creates: "{{ venv_directory }}"
